apiVersion: v1
kind: ConfigMap
metadata:
  name: local-volume-provider-config
  namespace: velero
  labels:
    velero.io/plugin-config: ""
    neridio.io/nfs: ObjectStore
    neridio.io/hostpath: ObjectStore
data:
  fileserverImage: 
  securityContextRunAsUser: "1001"
  securityContextFsGroup: "1001"
